version: "3.9"
services:
  postgres:
    image: postgres:14.15-alpine3.20
    container_name: my_postgres
    env_file:
      - ".env"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 20s
      timeout: 10s
      retries: 5
      start_period: 10s
    ports:
      - "5432:5432"
volumes:
  habrdb-data: